### ISSUE TITLE
Please add descriptions for github repo and in README + screenshots

### ISSUE THREAD

**Issue by luzpaz** [juanvanyo/FreeCAD-GDT#1]
This looks promising. Do you mind adding descriptions to:
* the github repo summary 
* the README.md file 
* screenshots

Thanks!

**Comment by luzpaz** [comment]
bump

**Comment by juanvanyo** [comment]
At the moment you can not work with the current version. When there is a more advanced version I will add all the descriptions pertinents

Sorry for the inconvenience

**Comment by juanvanyo** [comment]
Ready

**Comment by luzpaz** [comment]
Awesome! 
Can ou add the forum thread you created on FC for people who want to discuss further details with you?
Also, are you planning on having this added to github.com/FreeCAD/FreeCAD-addons ?

**Comment by juanvanyo** [comment]
I just added the link to the forum thread in the README.md
Sounds interesting add this project to github.com/FreeCAD/FreeCAD-addons . Do you have to meet a requirement to add it? What do I have to do to add my module there?
Thanks.

**Comment by luzpaz** [comment]
Open an issue in the add-ons repo and talk to yorik about adding this project

**Comment by juanvanyo** [comment]
Ok, thanks.
I close the issue.

**Comment by luzpaz** [comment]
Please add a description for this repo + tag the repo 'freecad'

**Comment by luzpaz** [comment]
@juanvanyo 
![image](https://user-images.githubusercontent.com/4140247/44542891-17f8d700-a6dc-11e8-9411-06945bf13b71.png)

Also tag the repo with 'freecad' please
